# Generated by Django 3.0.6 on 2020-06-03 21:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_aboutustext'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutustext',
            name='button',
            field=models.CharField(default='What do we do? ', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='button_ru',
            field=models.CharField(default='Чем мы занимаемся?', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='button_ua',
            field=models.CharField(default='Чим ми займаємося?', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step1_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step1_text_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step1_text_ua',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step1_title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step1_title_ru',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step1_title_ua',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step2_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step2_text_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step2_text_ua',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step2_title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step2_title_ru',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step2_title_ua',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step3_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step3_text_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step3_text_ua',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step3_title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step3_title_ru',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step3_title_ua',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step4_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step4_text_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step4_text_ua',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step4_title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step4_title_ru',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='step4_title_ua',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='subtext',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='subtext_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='subtext_ua',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='subtitle',
            field=models.CharField(default='Need an agile team?', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='subtitle_ru',
            field=models.CharField(default='Нужна креативная команда?', max_length=60),
        ),
        migrations.AddField(
            model_name='aboutustext',
            name='subtitle_ua',
            field=models.CharField(default='Потрібна креативна команда?', max_length=60),
        ),
        migrations.AlterField(
            model_name='aboutustext',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutustext',
            name='text_ru',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='aboutustext',
            name='text_ua',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
