# Generated by Django 3.0.7 on 2020-06-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_clientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientimage',
            name='image',
            field=models.FileField(upload_to='clients/'),
        ),
    ]
